### ISSUE TITLE
Document can't be re-opened after saving

### ISSUE THREAD

**Issue by Vitaliy-1** [kaschioudi/ojs3-markup#37] opened 2017-10-05 07:46 UTC
If one has edited a document with texture and saved it, result XML can't be opened anymore:

```
Uncaught (in promise) Error: ParserError: [object HTMLUnknownElement]
    at _check (substance.js:15034)
    at Function.BrowserDOMElement.parseMarkup (substance.js:15014)
    at Object.DefaultDOMElement.parseXML (substance.js:26172)
    at Texture.<anonymous> (texture.js:5730)
    at store.js:9
    at <anonymous>
```

**Comment by axfelix** [comment] 2017-10-05 15:42
@kaschioudi , are we writing out the file with additional HTML? I'm not actually sure I've tested the save/load behaviour since the most recent version bump, this is a weird regression but it's not impossible for us not to have caught it. I'll see if I can reproduce...

**Comment by kaschioudi** [comment] 2017-10-05 16:27
> are we writing out the file with additional HTML?

I don't think so. 

@axfelix  However on Aug 31st I reported a similar issue on slack (#xml) regarding `FigComponent` error when trying to re-open a document previously edited with Texture. Do you remember? I wonder if this is related. 

@Vitaliy-1 Could you send me your xml document so that I can try to reproduce this?

**Comment by axfelix** [comment] 2017-10-05 16:31
Yeah, we know we have problems with graphic elements of all kinds right now, their restrictive JATS subset doesn't like the way that meTypeset or Cermine is creating fig+caption: https://github.com/substance/texture/issues/252

I haven't written a block to "reorganize" all figs in our Merge module yet mostly due to my dislike of PHP DOM stuff & their intent to fix this in their next major release, but I probably should, as it's our only really significant blocker at the moment...

But @Vitaliy-1 's error looks different

**Comment by kaschioudi** [comment] 2017-10-05 16:53
Okay @axfelix. Were you able to reproduce the error? if so please send me your xml document so that I can try as well.

**Comment by axfelix** [comment] 2017-10-05 16:58
Haven't tested yet, I will a little later today

**Comment by axfelix** [comment] 2017-10-05 21:08
Yeah, I can duplicate this -- it's on Substance's end, though, I'll raise it with them.

**Comment by axfelix** [comment] 2017-10-05 21:11
https://github.com/substance/texture/issues/279

**Comment by Vitaliy-1** [comment] 2017-10-06 03:37
Example:
https://fex.net/get/018465473271/62275823

**Comment by Vitaliy-1** [comment] 2017-10-06 03:49
I suggest to check second DOCTYPE declaration, that is automatically added after the saving:
`<!DOCTYPE article PUBLIC "JATS4R 1.1" "http://texture.substance.io/JATS4R-1.1.dtd">` 
As well as additional `pub-id`'s

File after saving> Additional doctype declaration has been removed for proper formatting:
https://fex.net/get/018465473271/62277755

**Comment by axfelix** [comment] 2018-02-08 21:17
This should be fixed in Texture Alpha 4, which we'll be bringing upstream in the next month or so.

**Closed as completed by axfelix** 2018-02-08 21:17 UTC
